### ISSUE TITLE
not able to install the pod for a given project

### ISSUE THREAD

**Issue by DESHPANDE-1986** [QueryKit/RxQueryKit#2]
how can i install this pod, given pod is not working/ installing.

**Comment by kylef** [comment]
> how can i install this pod, given pod is not working/ installing.

You didn't provide any information on what the problem is so not really much I can say.

- How is installation not working?
- What error messages did you see?
- What steps did you try?
- What versions of tools are you using?

**Comment by DESHPANDE-1986** [comment]
Here are few details,
How is installation not working?
**as mentioned in documentation when i try to install the pod 'RXQuiryKit' i am getting the error: **
What error messages did you see?
**attached screen shot**
What steps did you try?
i was trying to install pod 'RXQuiryKit' 
What versions of tools are you using?
i am working on xcode 8/swift 3.0

**Comment by DESHPANDE-1986** [comment]
fixed it never mind
